app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
    path('virat/',virat,name='virat'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name="app2"
urlpatterns=[
    
path('rohit/',rohit,name='rohit'),
path('sachin/',sachin,name='sachin'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('app1/',include('app1.urls')),
    
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

def virat(request):
    return render(request,'virat.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

def sachin(request):
    return render(request,'sachin.html')

templates/dhoni.html
<html>
    <title>dhoni</title>
<body>

    <center>
        <h1> This is the app1 function1</h1>
        <h1 style="color:green">welcome to mr.dhoni</h1>
        <h2>Mahendra Singh Dhoni (Mahendra Singh Dhoni,born 7 July 1981), commonly known as MS Dhoni,
             is a former Indian cricketer and captain of the Indian national team in limited-overs formats from 2007 to 2017, 
             and in Test cricket from 2008 to 2014. He is also the current captain of Chennai Super Kings in the Indian Premier League. 
             Under his captaincy, India won the 2007 ICC World Twenty20, the 2011 Cricket World Cup, and the 2013 ICC Champions Trophy, 
             the most by any captain.He also led India to victory in the 2010 and 2016 Asia Cup. Additionally, under his leadership,
             India won the 2010 and 2011 ICC Test Mace and 2013 ICC ODI Championship. Dhoni is a right-handed wicket-keeper batsman known
              for his calm captaincy and his ability to finish matches in tight situations. 
            Mahi scored 17,266 runs in International Cricket (including 10,000 plus runs in ODI Internationals) and 
              is considered one of the best finishers in the game. He is also one of the greatest wicket-keepers\n


        <h3><a href="{% url 'app1:virat' %}">go to virat page</a></h3>
        <h3><a href="{% url 'app2:rohit' %}">go to rohit page</a></h3>
        <h3><a href="{% url 'app2:sachin' %}">go to sachin page</a></h3>

    </center>
</body>
</html>

templates/rohit.html
<html>
    <title>rohit</title>
<body>

    <center>
        <h1> This is the app2 function1</h1>
        <h1 style="color:red">welcome to mr.rohit</h1>
        <h2>Rohit Gurunath Sharma (born 30 April 1987), is an Indian international cricketer and the current captain of India men’s
            cricket team in all formats. Considered as one of the best batsman of his generation and one of greatest opening batters
            of all time, Rohit is known for his timing, elegance, six-hiting abilities and leadership skills. He plays as a
            right-handed batsman for India national cricket team in international cricket, Mumbai Indians in IPL and for Mumbai in
            domestic cricket. Rohit also captains Mumbai Indians and the team has won 5 titles under his leadership, the most by any team.

            Sharma currently holds the world record for the highest individual score (264) in a One Day International (ODI) 
            match and is the only player to have scored three double-centuries in ODIs and also holds the record for scoring
            most hundreds (five) in a single Cricket World Cup, for which he won the ICC Men's ODI Cricketer of the Year award in 2019.
            Sharma has received two national honours, the Arjuna Award in 2015 and the prestigious Major Dhyan Chand Khel Ratna in 2020.\




            <h3><a href="{% url 'app1:dhoni' %}">go to dhoni page</a></h3>
            <h3><a href="{% url 'app1:virat' %}">go to virat page</a></h3>
            <h3><a href="{% url 'app2:sachin' %}">go to sachin page</a></h3>
    
    </center>
</body>
</html>

templates/sachin.html
<html>
    <title>sachin</title>
<body>

    <center>
        <h1> This is the app2 function2</h1>
        <h1 style="color:orange">welcome to mr.sachin</h1>
        <h2>Sachin Ramesh Tendulkar BR,born 24 April 1973) is an Indian former international cricketer who captained the
             Indian national team. Nicknamed "The Little Master" and "Master Blaster, he is regarded as one of the 
             greatest batsmen in the history of cricket.He is the all-time highest run-scorer in both ODI and Test cricket 
             with more than 18000 runs and 15000 runs respectively in total.He also holds the record for receiving the
              most man-of-the-match awards in international cricket. Known for his large fanbase and described by ESPNcricinfo 
              as 'the most worshipped player in the world'.


              <h3><a href="{% url 'app1:virat' %}">go to virat page</a></h3>
              <h3><a href="{% url 'app2:rohit' %}">go to rohit page</a></h3>
              <h3><a href="{% url 'app1:dhoni' %}">go to dhoni page</a></h3>
      
    </center>
</body>
</html>

templates/virat.html
<html>
    <title>virat</title>
<body>

    <center>
        <h1> This is the app1 function2</h1>
        <h1 style="color:blue">welcome to mr.virat</h1>
        <h2>Virat Kohli ( born 5 November 1988) is an Indian international cricketer and former captain of the India national team 
            who plays as a right-handed batsman for Royal Challengers Bangalore in the IPL and for Delhi in Indian domestic cricket.
             Widely regarded as one of the greatest batsmen of all time, Kohli holds the records for scoring most runs in T20 
             internationals and in the IPL. In 2020, the International Cricket Council named him the male cricketer of the decade. 
             Kohli has also contributed to India's successes, including winning the 2011 World Cup and the 2013 Champions trophy.

        <h3><a href="{% url 'app1:dhoni' %}">go to dhoni page</a></h3>
        <h3><a href="{% url 'app2:rohit' %}">go to rohit page</a></h3>
        <h3><a href="{% url 'app2:sachin' %}">go to sachin page</a></h3>

    </center>
</body>
</html>